version: "3.8"
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rails:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
    command: ./entrypoint.sh
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
